spring:
  application:
    name: KnowFlowAI

  datasource:
    url: jdbc:mysql://localhost:3306/knowflow_ai
    username: root
    password: Bakliwal@mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-mini

springdoc:
  swagger-ui:
    path: /swagger-ui.html